# Generated by Django 6.1.1 on 2026-09-12 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('activity_type', models.CharField(choices=[('reading', 'Reading'), ('coding', 'Coding Exercise'), ('quiz', 'Quiz'), ('assignment', 'Assignment'), ('lab', 'Lab')], max_length=20)),
                ('instructions', models.TextField()),
                ('order', models.PositiveIntegerField(default=1)),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('is_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='academy.lesson')),
            ],
        ),
    ]
