# Generated by Django 6.1.1 on 2026-09-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0017_quizanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional supporting file for an assignment/lab submission.', null=True, upload_to='submissions/'),
        ),
        migrations.AddField(
            model_name='submission',
            name='github_url',
            field=models.URLField(blank=True, help_text='Optional GitHub repository or submission URL.'),
        ),
        migrations.AddField(
            model_name='submission',
            name='response_text',
            field=models.TextField(blank=True, help_text='Written response or explanation for assignment/lab submissions.'),
        ),
    ]
