services:
  - type: web
    name: coding-e-learning-platform
    runtime: python
    rootDir: backend
    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        sync: false
      - key: PYTHON_VERSION
        value: "3.12"
